baseURL: "http://example.org/" #TODO: update
languageCode: "en-us"
theme: "anubis"
paginate: 10
#disqusShortname: ""
#googleAnalytics: "G-1234"
enableRobotsTXT: true
defaultContentLanguage: en

languages:
  en:
    languageName: "English"
    title: "Robby's RV-7A Build Log"

  ru:
    languageName: "Russian"
    title: "Журнал сборки RV-7A Робби"
    params:
      author: "Робби Вайнберг"
    menu:
      main:
        - identifier: about
          name: about
          title: about
          url: /about/
          weight: 0
        - identifier: archive
          name: записи
          title: записи
          url: /posts/
          weight: 0
        - identifier: tags
          name: теги
          title: теги
          url: /tags/
          weight: 0

menu:
  main:
    - identifier: about
      name: about
      title: about
      url: /about/
      weight: 0
    - identifier: archive
      name: archive
      title: archive
      url: /posts/
      weight: 0
    - identifier: tags
      name: tags
      title: tags
      url: /tags/
      weight: 0

params:
  author: "Robby Weinberg"
  email: robbyj.weinberg@gmail.com
  description: ""
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: auto # light-without-switcher
  readmore: false
  readNextPosts: 5
  disableSummary: false
  copyCodeButton: true
  rssAsSocialIcon: true

taxonomies:
  category: "categories"
  tag: "tags"
