baseURL: "https://jocular-sprite-0c8a2d.netlify.app" #TODO: update
languageCode: "en-us"
theme: "PaperMod-Robby"
paginate: 10
#disqusShortname: ""
#googleAnalytics: "G-1234"
enableRobotsTXT: true
defaultContentLanguage: en
displayFullLangName: true

languages:
  en:
    languageName: "English"
    title: "Robby's RV-7A Build Log"

  ru:
    languageName: "Russian"
    title: "Журнал сборки RV-7A Робби"
    params:
      author: "Робби Вайнберг"
    menu:
      main:
        - identifier: about
          name: about
          title: about
          url: /about/
          weight: 0
        - identifier: archive
          name: записи
          title: записи
          url: /posts/
          weight: 0
        - identifier: tags
          name: теги
          title: теги
          url: /tags/
          weight: 0
        - identifier: search
          name: поиск
          title: поиск
          url: /search/
          weight: 0

menu:
  main:
    - identifier: about
      name: about
      title: about
      url: /about/
      weight: 0
    - identifier: archive
      name: archive
      title: archive
      url: /posts/
      weight: 0
    - identifier: tags
      name: tags
      title: tags
      url: /tags/
      weight: 0
    - identifier: search
      name: search
      title: search
      url: /search/

params:
  author: "Robby Weinberg"
  email: robbyj.weinberg@gmail.com
  description: "Vans RV-7A Project Build Log by Robby Weinberg"
  dateFormat: "January 2006"
  defaultTheme: auto
  # paginationSinglePost: true
  # style: auto # light-without-switcher
  # readmore: false
  # readNextPosts: 5
  # disableSummary: false
  # copyCodeButton: true
  # rssAsSocialIcon: true
  # ShowBreadCrumbs: true

taxonomies:
  category: "categories"
  tag: "tags"

outputs:
  home:
    - HTML
    - RSS
    - JSON